# Generated by Django 4.2.7 on 2023-11-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='nome_faculdade',
            field=models.IntegerField(choices=[(1, 'BAIRRO CIDADE NOBRE'), (2, 'BAIRRO HORTO'), (3, 'BAIRRO VENEZA')]),
        ),
    ]
