# Generated by Django 4.2.7 on 2023-11-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_nome_faculdade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='nome_faculdade',
            new_name='nome_campus',
        ),
    ]
